# https://docs.github.com/fr/actions/use-cases-and-examples/creating-an-example-workflow
name: analyse-statique-et-tests-unitaires
run-name: ${{ github.actor }} initiated ${{ github.event_name }} starting ${{ github.workflow }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  analyse-statique-et-tests-unitaires:
    runs-on: [self-hosted, x64, linux]
    steps:

      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Installation des dépendances avec Composer
        run: composer install --prefer-dist

      - name: Analyse statique du code avec PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Exécution des tests unitaires avec PHPUnit
        run: ./vendor/bin/phpunit

      - name: Analyse et tests terminés avec succès
        run: echo "✅ Tous les contrôles sont passés avec succès !"
