# https://docs.github.com/fr/actions/use-cases-and-examples/creating-an-example-workflow
name: analyse-statique-et-tests-unitaires
run-name: ${{ github.actor }} initiated ${{ github.event_name }} starting ${{ github.workflow }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, x64, linux, ephemeral]
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Installation des dépendances avec Composer
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Analyse statique du code avec PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Exécution des tests unitaires avec PHPUnit
        run: ./vendor/bin/phpunit

      - name: Analyse et tests terminés avec succès
        run: echo "✅ Tous les contrôles sont passés avec succès !"
